import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <meta
                    name='description'
                    content='שירותי הובלה מקצועיים לדירות, משרדים ופריטים מיוחדים. אמינות, מקצועיות וזמינות גבוהה. קבלו הצעת מחיר מותאמת אישית!'
                />
                <meta
                    name='keywords'
                    content='שירותי הובלה, הובלות דירות, הובלות משרדים, שירותי מנוף, הובלות קטנות, ביטוח הובלות'
                />
                <meta name='author' content='צ׳יק צ׳ק הובלות' />
                <meta name='viewport' content='width=device-width, initial-scale=1.0' />

                {/* Open Graph for Social Media */}
                <meta property='og:title' content='שירותי הובלה מקצועיים - מובילים באיכות' />
                <meta
                    property='og:description'
                    content='שירותי הובלה מקצועיים לדירות, משרדים ופריטים מיוחדים. אמינות, מקצועיות וזמינות גבוהה. קבלו הצעת מחיר מותאמת אישית!'
                />
                <meta property='og:url' content='https://chikchak-hovalot.vercel.app' />
                <meta property='og:type' content='website' />

                {/* Twitter Cards */}
                <meta name='twitter:card' content='summary_large_image' />
                <meta name='twitter:title' content='שירותי הובלה מקצועיים - מובילים באיכות' />
                <meta
                    name='twitter:description'
                    content='שירותי הובלה מקצועיים לדירות, משרדים ופריטים מיוחדים. אמינות, מקצועיות וזמינות גבוהה. קבלו הצעת מחיר מותאמת אישית!'
                />
                {children}
            </body>
        </html>
    );
}
